# fir.S
# assembly language of Finite Impulse Response (FIR)

// a0: base address of x
// a1: base address of c
// a2: base address of y, later used as pointer to y[j] in j loop
// a3: n
// a4: m

// t0: &y[n-m+1] to check termination of j loop
// t1: &c[m] to check termination of i loop
// t2: &x[j+m-1]
// t3: sum
// t4: pointer to c[i] in i loop
// t5: pointer to x[j-i+(m-1)]
// t6: value of c[i]
// a5: value of x[j-1+(m-1)]

.global fir

fir:

    lw   t1, 4(a0)        # t1 = x[0+4];
    lw   t2, 4(a1)        # t2 = c[0+4];
    addi t3, zero, 42


donej:
    ret                 # all done; return
